export const FACEBOOK_URL = 'https://www.facebook.com/Aries-Living-112940767034421/'
export const TWITTER_USER_NAME = 'https://twitter.com/aries_living'
export const INSTAGRAM_USER_NAME = 'https://instagram.com/ariesliving'
export const NAME_SHORT = 'Ithaca'
export const LLC_NAME = 'Ithaca Hotel YT AL LLC'
export const NAME_LONG = 'of South Beach Hotel'
export const EMAIL_ADDRESS = 'ithaca@ariesliving.com'
export const PHONE_NUMBER = '+1 (813) 575-4532'
export const PLATFORM_LOWERCASE = 'ithaca of south beach hotel'
export const ADDRESS_TOP = '601 Collins Ave'
export const ADDRESS_BOTTOM = 'Miami Beach, FL 33139'
export const PLATFORM_URL = 'https://ithacasouthbeach.com'
export const defaultOgImage =
  'https://res.cloudinary.com/dqtpoczux/image/upload/v1595527351/og_ejou0x.png'
